--CREATE DB STAGE
IF EXISTS (SELECT name FROM master.sys.databases WHERE name = N'SUPERMARKET_SALES_STAGE')
	DROP DATABASE SUPERMARKET_SALES_STAGE;
CREATE DATABASE SUPERMARKET_SALES_STAGE;
GO

--CREATE DB NDS
IF EXISTS (SELECT name FROM master.sys.databases WHERE name = N'SUPERMARKET_SALES_NDS')
	DROP DATABASE SUPERMARKET_SALES_NDS;
CREATE DATABASE SUPERMARKET_SALES_NDS;
GO

--CREATE DB DDS
IF EXISTS (SELECT name FROM master.sys.databases WHERE name = N'SUPERMARKET_SALES_DDS')
	DROP DATABASE SUPERMARKET_SALES_DDS;
CREATE DATABASE SUPERMARKET_SALES_DDS;
GO

--CREATE DB METADB
IF EXISTS (SELECT name FROM master.sys.databases WHERE name = N'SUPERMARKET_SALES_METADB')
	DROP DATABASE SUPERMARKET_SALES_METADB;
CREATE DATABASE SUPERMARKET_SALES_METADB;
GO